config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  if Rails.env.development?
    post "/auth/:provider/callback", to: "sessions#create"# this is required for the OmniAuth Developer Strategy
  end

  post "/auth/:provider", to: "sessions#create", as: "login"
  get "/auth/:provider/callback", to: "sessions#create"

  get "/login", to: "sessions#index", as: "landing"
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/dashboard/:stalker_id" => "stalkers#index", as: "dashboard"

  post "/search", to: "searches#search"
  get "/search/:client/:search_term", to: "searches#show", as: "search_results"

  post "/follow" => "prey#create", as: "follow"
  patch "/unfollow", to: "prey#unfollow", as: "unfollow"

  post "/", to: "posts#update_feed", as: "update_feed"

end

app/views/shared/_error.html.erb
<h2 class="error-message"><%= message %></h2>
<div class="row-centered">
  <div class="col-centered">
    <%= link_to image_tag("notso-2.png", class: "animated hinge"), root_path %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if !flash.empty? %>
  <div id="flash">
    <%= flash[:errors] %>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash[:success] %>
  <div>
    <p class="alert alert-success"><%= flash[:success] %></p>
  </div>
<% end %>

<% if flash[:errors] %>
  <div>
    <p class="alert alert-danger"><%= flash[:errors] %></p>
  </div>
<% end %>

app/views/shared/_following_list.html.erb
<table class="table">
  <% all_prey.each do |prey| %>
    <tr>
      <td>
        <%= image_tag prey.photo_url, class: "media-object" %>
      </td>
      <td>
        <h4><%= link_to prey.username, prey.profile_url, class: "media-heading" %></h4>
      </td>
      <td>
        <%= button_to "Unfollow", unfollow_path, class: "btn btn-danger btn-sm",
          method: :patch,
          params: {
            uid: prey.uid,
            provider: prey.provider
          }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/_header.html.erb
<nav class="nav navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to root_path do %>
          <i class="glyphicon glyphicon-sunglasses"></i>
        <% end %>
      </li>
      <li><%= link_to "Feed", feeds_path %></li>
      <li><%= link_to "Search Twitter", search_path('twitter')  %></li>
      <li><%= link_to "Search Instagram", search_path('instagram') %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text"> Stay weird, <%= user_or_guest %></p></li>
      <% if session[:user_id] %>
        <li><%= button_to("Sign Out", logout_path, method: :delete, class: "btn btn-default navbar-btn") %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_instauser.html.erb
<% @response.each do |person| %>
  <tr>
  <td><%= image_tag(person["profile_picture"]) %></td>
  <td><%= person["username"] %></td>
  <td><%= person["full_name"] %></td>

  <% if @user.already_subscribed?(person["id"]) %>
  <td><h5 class="btn btn-default">Already Fed!</h5></td>
  <% else %>
  <td><%= link_to "Feed the Beast!", ig_subscriptions_path(
      params: {
      instagram_id: person["id"],
      profile_pic: person["profile_picture"] } ),
      method: :post, class: "btn btn-default"  %></td>
  </tr>
  <% end %>
<% end %>

app/views/shared/_internal_posts.html.erb
<% @posts.each do |post| %>
  <div class="feed">
    <% if post.feed.platform == "Instagram" %>
      <%= image_tag post.content, class: "left" %>
    <% elsif post.feed.platform == "Vimeo" %>
      <div class ="center">
        <%= post.content.html_safe %>
      </div>
    <% end %>
      <h3>
        <% if post.feed.platform == "Instagram" %>
          <div class="right">
            <%= link_to post.feed.name, instagram_feed_path(post.feed.platform_feed_id) %>
            <span class="badge">
              <%= number_with_delimiter(post.likes, :delimiter => ',') %> likes
            </span>
          </div>
        <% elsif post.feed.platform == "Vimeo" %>
          <%= link_to post.feed.name, vimeo_feed_path(post.feed.platform_feed_id) %>
          <span class="badge">
            <%= number_with_delimiter(post.likes, :delimiter => ',') %> likes
          </span>
        <% end %>
      </h3>
      <% if post.feed.platform == "Instagram" %>
        <p class="right">
          <% if post.description %>
            <%= post.description %>
          <% else %>
            No description provided.
          <% end %>
        </p>
      <% elsif post.feed.platform == "Vimeo" %>
        <p>
          <% if post.description %>
            <%= post.description %>
          <% else %>
            No description provided.
          <% end %>
        </p>
      <% end %>
    <div class="date">
      <%= display_pacific_time(post.date_posted) %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
  <nav class="container navbar navbar-inverse">
  <% if @user && session[:user_id]%>
    <div class ="navbar-text navbar-left"><%= @user.username %></div>
  <% end %>
  <ul class="nav navbar-nav navbar-right">
  <% if session[:user_id].nil? %>
    <% unless Rails.env.production? %>
        <li><%= link_to "Dev Login", login_path(provider: :developer) %></li>
    <% end %>
  <% else %>
    <%# link_to "Refresh", root_path, class: "btn btn-default btn-feed" %>
    <li><%= link_to root_path, class: "btn btn-feed" do %>
      <i class="glyphicon glyphicon-repeat"></i>
    <% end %></li>
    <li><%= link_to "Stalk Targets", search_path %></li>
    <li><%= link_to "Assasinate", people_path %></li>
    <li><%= link_to "Go Home", root_path, method: :get %></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
    <% unless Rails.env.production? %>
      <li><%= link_to "Dev Login", login_path(provider: :developer) %></li>
    <% end %>
  <% end %>
  </ul>
</nav>

app/views/shared/_postthumbnail.html.erb
<% @posts.each do |post| %>
  <div class="col-md-10 col-md-offset-1">
    <div class="thumbnail">
      <div class="user">
      <%= image_tag(post.subscription.profile_pic, class: "img-circle prof-pic") %>
      <p class="posted-at"> posted <%= time_ago_in_words(post.posted_at) %> ago </p>
      <% if post.subscription.twitter_id.present? %>
        <i class="fa fa-twitter"></i>
      <% else %>
        <i class="fa fa-instagram"></i>
      <% end %>
      <%= link_to "#{post.username}", posts_path(post.username, username: post.username) %>
      </div>
      <% unless post.image.empty? %>
        <% post.image.each do |image| %>
          <%= image_tag(image, class: "img-rounded fix-width") %>
        <% end %>
      <% end %>
      <div class="caption text-center">
        <%= post.text %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
<%= form_for :search, url: search_path do |f| %>

  <div class="row">
    <%= f.text_field :query, placeholder: "user name" %>
    <label>
      Instagram
        <%= f.radio_button :platform, "Instagram" %>
    </label>

    <label>
      Vimeo
      <%= f.radio_button :platform, "Vimeo" %>
    </label>
    <%= f.submit "Search", class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_for provider, url: url, html: { class: "form-inline" } do |f| %>
  <%= f.label :username, "Search #{provider.to_s.titlecase} Users", class: "search-header" %><br>
  <%= f.text_field :username, :size => 50, placeholder: "Search Users", class: "form-control form-group search" %>
  <%= button_tag(type: 'submit', class: "btn btn-primary search") do %>
    <span class="glyphicon glyphicon-search"></span>
  <% end %>
<% end %>

app/views/shared/_twitteruser.html.erb
<% @response.each do |person| %>
<tr>
  <td><%= image_tag person.profile_image_url %></td>
  <td><%= person.screen_name %></td>
  <td><%= person.name %></td>
  <% if @user.already_subscribed?(person.id) %>
    <td><h5 class="btn btn-default">Already Fed!</h5></td>
  <% else %>
    <td><%= link_to "Feed the BEAST!", twi_subscriptions_path(
      params: {
      twitter_id: person.id,
      profile_pic: person.as_json["profile_image_url"] }),
      method: :post,
      class: "btn btn-default" %>
    </td>
  <% end %>
<% end %>

app/views/shared/_update.html.erb
<% @show_posts.each do |p| %>
  <!-- "raw" tells the browser that it is to be embedded as html -->
    <%= raw p.embed_html %>
  <% end %>

app/views/shared/_usersearch.html.erb
<table class="table table-hover">
<% unless @response.empty? %>
  <th>Pic</th>
  <th>Username</th>
  <th>Name</th>
  <th>Subscribe</th>
  <% if @response.first.class == Hash %>
    <%= render 'shared/instauser' %>
  <% else %>
    <%= render 'shared/twitteruser' %>
  <% end %>
<% else %>
  <h4><center>The beast could not find any friends to eat. Please search again!</h4>
<% end %>
    </tr>
</table>