config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  if Rails.env.development?
    post "/auth/:provider/callback", to: "sessions#create"# this is required for the OmniAuth Developer Strategy
  end

  post "/auth/:provider", to: "sessions#create", as: "login"
  get "/auth/:provider/callback", to: "sessions#create"

  get "/login", to: "sessions#index", as: "landing"
  delete "/logout" => "sessions#destroy", as: "logout"

  get "/dashboard/:stalker_id" => "stalkers#index", as: "dashboard"

  post "/search", to: "searches#search"
  get "/search/:client/:search_term", to: "searches#show", as: "search_results"

  post "/follow" => "prey#create", as: "follow"
  patch "/unfollow", to: "prey#unfollow", as: "unfollow"

  post "/", to: "posts#update_feed", as: "update_feed"

end

app/controllers/searches_controller.rb
require 'instagram_client'
class SearchesController < ApplicationController
  def search
    if params[:search].empty?
      redirect_to root_path
    else
      redirect_to search_results_path(params[:client], params[:search])
    end
  end

  def show
    if params[:client] == "twitter"
      @prey = TwitterClient.user_search(params[:search_term])
    elsif params[:client] == "instagram"
      @prey = InstagramClient.user_search(params[:search_term])
    end
  end
end

app/views/searches/index.html.erb
<h1>Search results for <%= params[:search_twitter] %>  </h1>

<ul>
  <% @search_results.each do |user| %>
    <ul>USER ID: <%= user %></ul>
  <% end %>
</ul>

app/views/searches/show.html.erb
<h1>Search results for <%= params[:search_term] %>  </h1>

<div class="row">
  <% @prey.each do |prey| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(prey[:photo_url], alt: "Profile Picture" ), prey[:profile_url]) %>
        <div class="caption">
          <center>
            <h3>
              <%= link_to prey[:username], prey[:profile_url] %>
              <br>
              <%= button_to "Follow", follow_path, class: "btn btn-primary active",
                method: :post, params: {
                  uid: prey[:uid],
                  name: prey[:name],
                  username: prey[:username],
                  provider: prey[:provider],
                  photo_url: prey[:photo_url],
                  profile_url: prey[:profile_url]
                }
              %>
            </h3>
          </center>
        </div>

      </div>
    </div>
  <% end %>
</div>